config/routes.rb
Nodetree::Application.routes.draw do
  resources :notes

   root :to => "notes#index"

end

app/models/note.rb
require 'github/markup'

class Note < ActiveRecord::Base
  SUPPORTED_MARKUPS = ["markdown","textile"]
  has_many :children, :class_name => "Note", :foreign_key => "parent_id"
  belongs_to :parent, :class_name => "Note", :foreign_key => "parent_id"
  
  def to_html(markup = "markdown")
    raise UnsupportedMarkup unless SUPPORTED_MARKUPS.include?(markup)
    GitHub::Markup.render(".#{markup}", self.content)
  end
    
  
  def self.print_tree
    notes = where(:parent_id => 0)
    notes.each do |note|
      note.print_tree(0)
    end
  end
  
  def print_tree(depth)
    p leader(depth) + name
    children.each do |child|
      child.print_tree(depth+1)
    end
  end
  
  def self.print_html_tree
    notes = where(:parent_id => 0)
    html = ""
    notes.each do |note|
      html += note.print_html_tree
    end
    html
  end
  
  def print_html_tree
    html = "<div id='node-#{id}'>" + "<img src='images/minus.png' onclick='toggle_tree(#{id})' height=20 width=20>" + "<a onclick='show_note(#{id});'>" + name + "</a>"
    children.each do |child|
      html += child.print_html_tree
    end
    html += "</div>"
  end
  
  def leader(depth)
    leader = ""
    depth.times {leader=leader+'-'}
    leader = leader + '>' 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  def index
    @notes = Note.select("id, name, content, parent_id").where(:parent_id=>0)

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @notes.map{|n| n.attributes}}
    end
  end

  # GET /notes/1
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @note }
    end
  end

  # GET /notes/new
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to(@note, :notice => 'Note was successfully created.') }
        format.json  { render :json => @note, :status => :created, :location => @note }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to(@note, :notice => 'Note was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to(notes_url) }
      format.json  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nodetree</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body class="bp">
  <div id="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.text_field :parent_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/_index.html.erb
<table>
  <tr>
    <th>Content</th>
    <th>Parent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= note.content %></td>
    <td><%= note.parent %></td>
    <td><%= link_to 'Show', note %></td>
    <td><%= link_to 'Edit', edit_note_path(note) %></td>
    <td><%= link_to 'Destroy', note, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Note', new_note_path %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<div id="tree" class="span-8">
Loading Tree...
</div>
<div id="note" class="span-14 last">
Loading...
</div>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @note.content %>
</p>

<p>
  <b>Parent:</b>
  <%= @note.parent %>
</p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>